### ISSUE TITLE
SSDT is causing Windows BSOD: WDF_Violation.

### ISSUE THREAD

**Issue by Oschly** [osy86/USBWakeFixup#4]
Hello.
After adding SSDT-USBW + Kext to my OC bootloader, Windows throws BSOD when I am trying to boot it with OpenCore, giving code WDF_Violation.

[EFI](https://github.com/osy86/USBWakeFixup/files/3638693/EFI.zip)

Specification:
MOBO: MSI Z390 MAG Tomahawk
CPU: i7-8700k
GPU: Sapphire RX 580 Nitro+
RAM: 16GB DDR4 3200MHz

**Comment by osy86** [comment]
Did you update all the SSDT? Can you post your EFI/OC/ACPI?

**Comment by Oschly** [comment]
How should I update all my SSDTs?
Link to download my whole EFI is right above my specification list.

**Comment by osy86** [comment]
Ah I see. In my example, I didn't wrap it around in OSDW(), but I do that for my own build. Please see https://github.com/osy86/HaC-Mini/blob/master/ACPI/SSDT-Xhci.dsl#L372

I didn't include it because not everyone has OSDW(). Perhaps I should make that note in the readme. If you read OC's configuration pdf, they point out you need to wrap SSDT changes with `_OSI("Darwin")` which is what I do.

**Comment by osy86** [comment]
Please try https://github.com/osy86/USBWakeFixup/blob/master/SSDT-USBW.dsl

**Comment by Oschly** [comment]
Updated SSDT works (is disabled) great with Windows.
Thank You for help.
